## Import Data

In [149]:
import pandas as pd
csv_df = pd.read_csv('dataset.csv', encoding='latin')
csv_df

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,positivity,positivity:confidence,relevance,relevance:confidence,articleid,date,headline,positivity_gold,relevance_gold,text
0,842613455,False,finalized,3,12/5/15 17:48,3.0,0.6400,yes,0.6400,wsj_398217788,8/14/91,Yields on CDs Fell in the Latest Week,NaN,NaN,NEW YORK -- Yields on most certificates of dep...
1,842613456,False,finalized,3,12/5/15 16:54,NaN,NaN,no,1.0000,wsj_399019502,8/21/07,The Morning Brief: White House Seeks to Limit ...,NaN,NaN,The Wall Street Journal Online</br></br>The Mo...
2,842613457,False,finalized,3,12/5/15 1:59,NaN,NaN,no,1.0000,wsj_398284048,11/14/91,Banking Bill Negotiators Set Compromise --- Pl...,NaN,NaN,WASHINGTON -- In an effort to achieve banking ...
3,842613458,False,finalized,3,12/5/15 2:19,NaN,0.0000,no,0.6750,wsj_397959018,6/16/86,Manager's Journal: Sniffing Out Drug Abusers I...,NaN,NaN,The statistics on the enormous costs of employ...
4,842613459,False,finalized,3,12/5/15 17:48,3.0,0.3257,yes,0.6400,wsj_398838054,10/4/02,Currency Trading: Dollar Remains in Tight Rang...,NaN,NaN,NEW YORK -- Indecision marked the dollar's ton...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,830985632,False,finalized,3,11/17/15 18:16,7.0,0.3511,yes,0.6641,wapo_152454634,2/11/52,"Sawyer Sees Strong Economy For 2 Years, Truce ...",NaN,NaN,Secretary of Commerce Charles W. Sawyer said y...
7996,830985633,False,finalized,3,11/18/15 8:10,NaN,NaN,no,1.0000,wapo_410349039,12/13/09,Oil's losses are airlines' gains,NaN,NaN,"U.S. stocks inched up last week, overcoming co..."
7997,830985634,False,finalized,3,11/18/15 12:12,NaN,NaN,no,1.0000,wapo_410346237,12/18/09,Full Senate to vote on Bernanke; PANEL ADVANCE...,NaN,NaN,Ben S. Bernanke cleared a key hurdle Thursday ...
7998,830985635,False,finalized,3,11/18/15 7:17,NaN,0.0000,no,0.6855,wapo_307808606,1/10/95,Reinventing Opportunities,NaN,NaN,The White House's push to contract out many fe...
7999,830985636,False,finalized,3,11/18/15 11:05,NaN,NaN,no,1.0000,wapo_143151328,4/18/67,Stocks Rise On News of Auto Output: Dow Climbs...,NaN,NaN,NEW YORK. April 17-Automobile stocks put on th...

## Extract features

In [150]:
features_list = ['headline', 'text', 'relevance']
df = csv_df[features_list]
df

,headline,text,relevance
0,Yields on CDs Fell in the Latest Week,NEW YORK -- Yields on most certificates of dep...,yes
1,The Morning Brief: White House Seeks to Limit ...,The Wall Street Journal Online</br></br>The Mo...,no
2,Banking Bill Negotiators Set Compromise --- Pl...,WASHINGTON -- In an effort to achieve banking ...,no
3,Manager's Journal: Sniffing Out Drug Abusers I...,The statistics on the enormous costs of employ...,no
4,Currency Trading: Dollar Remains in Tight Rang...,NEW YORK -- Indecision marked the dollar's ton...,yes
...,...,...,...
7995,"Sawyer Sees Strong Economy For 2 Years, Truce ...",Secretary of Commerce Charles W. Sawyer said y...,yes
7996,Oil's losses are airlines' gains,"U.S. stocks inched up last week, overcoming co...",no
7997,Full Senate to vote on Bernanke; PANEL ADVANCE...,Ben S. Bernanke cleared a key hurdle Thursday ...,no
7998,Reinventing Opportunities,The White House's push to contract out many fe...,no
7999,Stocks Rise On News of Auto Output: Dow Climbs...,NEW YORK. April 17-Automobile stocks put on th...,no

In [151]:
df.groupby('relevance').count()

           headline  text
relevance
no             6571  6571
not sure          9     9
yes            1420  1420

## remove rows with label 'not sure'

In [152]:
df1 = df[df.relevance != 'not sure']
df1

,headline,text,relevance
0,Yields on CDs Fell in the Latest Week,NEW YORK -- Yields on most certificates of dep...,yes
1,The Morning Brief: White House Seeks to Limit ...,The Wall Street Journal Online</br></br>The Mo...,no
2,Banking Bill Negotiators Set Compromise --- Pl...,WASHINGTON -- In an effort to achieve banking ...,no
3,Manager's Journal: Sniffing Out Drug Abusers I...,The statistics on the enormous costs of employ...,no
4,Currency Trading: Dollar Remains in Tight Rang...,NEW YORK -- Indecision marked the dollar's ton...,yes
...,...,...,...
7995,"Sawyer Sees Strong Economy For 2 Years, Truce ...",Secretary of Commerce Charles W. Sawyer said y...,yes
7996,Oil's losses are airlines' gains,"U.S. stocks inched up last week, overcoming co...",no
7997,Full Senate to vote on Bernanke; PANEL ADVANCE...,Ben S. Bernanke cleared a key hurdle Thursday ...,no
7998,Reinventing Opportunities,The White House's push to contract out many fe...,no
7999,Stocks Rise On News of Auto Output: Dow Climbs...,NEW YORK. April 17-Automobile stocks put on th...,no

### convert yes/no to numeric values

In [153]:
# map yes/no to 0 or 1
map_labels = {'yes':1, 'no': 0}
# news_df['relevance'] = news_df['relevance'].apply(map_labels) # why does this not work??
# df2 = news_df['relevance'].map(map_labels)
# news_df.loc[:,news_df['relevance'].replace(to_replace=['no','not sure', 'yes'], value=[0, 0.5, 1])]
# df2
# df['Discounted_Price'] = df['Cost'] - (0.1 * df['Cost']) 
df1.loc[:,'relevance_point'] = df1['relevance'].map(map_labels)
df1

,headline,text,relevance,relevance_point
0,Yields on CDs Fell in the Latest Week,NEW YORK -- Yields on most certificates of dep...,yes,1
1,The Morning Brief: White House Seeks to Limit ...,The Wall Street Journal Online</br></br>The Mo...,no,0
2,Banking Bill Negotiators Set Compromise --- Pl...,WASHINGTON -- In an effort to achieve banking ...,no,0
3,Manager's Journal: Sniffing Out Drug Abusers I...,The statistics on the enormous costs of employ...,no,0
4,Currency Trading: Dollar Remains in Tight Rang...,NEW YORK -- Indecision marked the dollar's ton...,yes,1
...,...,...,...,...
7995,"Sawyer Sees Strong Economy For 2 Years, Truce ...",Secretary of Commerce Charles W. Sawyer said y...,yes,1
7996,Oil's losses are airlines' gains,"U.S. stocks inched up last week, overcoming co...",no,0
7997,Full Senate to vote on Bernanke; PANEL ADVANCE...,Ben S. Bernanke cleared a key hurdle Thursday ...,no,0
7998,Reinventing Opportunities,The White House's push to contract out many fe...,no,0
7999,Stocks Rise On News of Auto Output: Dow Climbs...,NEW YORK. April 17-Automobile stocks put on th...,no,0

#### reset index
observe above that the indices indicated in df1 goes from 0-7999 whereas it should go 0-7990. This problem actually resulted in NaN while concatenation done later.

In [154]:
df1.reset_index(drop=True, inplace=True)
df1

,headline,text,relevance,relevance_point
0,Yields on CDs Fell in the Latest Week,NEW YORK -- Yields on most certificates of dep...,yes,1
1,The Morning Brief: White House Seeks to Limit ...,The Wall Street Journal Online</br></br>The Mo...,no,0
2,Banking Bill Negotiators Set Compromise --- Pl...,WASHINGTON -- In an effort to achieve banking ...,no,0
3,Manager's Journal: Sniffing Out Drug Abusers I...,The statistics on the enormous costs of employ...,no,0
4,Currency Trading: Dollar Remains in Tight Rang...,NEW YORK -- Indecision marked the dollar's ton...,yes,1
...,...,...,...,...
7986,"Sawyer Sees Strong Economy For 2 Years, Truce ...",Secretary of Commerce Charles W. Sawyer said y...,yes,1
7987,Oil's losses are airlines' gains,"U.S. stocks inched up last week, overcoming co...",no,0
7988,Full Senate to vote on Bernanke; PANEL ADVANCE...,Ben S. Bernanke cleared a key hurdle Thursday ...,no,0
7989,Reinventing Opportunities,The White House's push to contract out many fe...,no,0
7990,Stocks Rise On News of Auto Output: Dow Climbs...,NEW YORK. April 17-Automobile stocks put on th...,no,0

## join headline and text

In [155]:
df1.loc[:,'all_text'] = df1['headline'] + ' ' + df1['text']
df1

,headline,text,relevance,relevance_point,all_text
0,Yields on CDs Fell in the Latest Week,NEW YORK -- Yields on most certificates of dep...,yes,1,Yields on CDs Fell in the Latest Week NEW YORK...
1,The Morning Brief: White House Seeks to Limit ...,The Wall Street Journal Online</br></br>The Mo...,no,0,The Morning Brief: White House Seeks to Limit ...
2,Banking Bill Negotiators Set Compromise --- Pl...,WASHINGTON -- In an effort to achieve banking ...,no,0,Banking Bill Negotiators Set Compromise --- Pl...
3,Manager's Journal: Sniffing Out Drug Abusers I...,The statistics on the enormous costs of employ...,no,0,Manager's Journal: Sniffing Out Drug Abusers I...
4,Currency Trading: Dollar Remains in Tight Rang...,NEW YORK -- Indecision marked the dollar's ton...,yes,1,Currency Trading: Dollar Remains in Tight Rang...
...,...,...,...,...,...
7986,"Sawyer Sees Strong Economy For 2 Years, Truce ...",Secretary of Commerce Charles W. Sawyer said y...,yes,1,"Sawyer Sees Strong Economy For 2 Years, Truce ..."
7987,Oil's losses are airlines' gains,"U.S. stocks inched up last week, overcoming co...",no,0,Oil's losses are airlines' gains U.S. stocks i...
7988,Full Senate to vote on Bernanke; PANEL ADVANCE...,Ben S. Bernanke cleared a key hurdle Thursday ...,no,0,Full Senate to vote on Bernanke; PANEL ADVANCE...
7989,Reinventing Opportunities,The White House's push to contract out many fe...,no,0,Reinventing Opportunities The White House's pu...
7990,Stocks Rise On News of Auto Output: Dow Climbs...,NEW YORK. April 17-Automobile stocks put on th...,no,0,Stocks Rise On News of Auto Output: Dow Climbs...

In [156]:
sample_text = df1.loc[4016,'all_text']
sample_text

"Farewell Blast For a Hotel In Pittsburgh A \x89Û÷\x89Û÷controlled implosion\x89Û\x9d (top) begins to crumble the 16-story Carlton House Hotel in downtown Pittsburgh Saturday morning. The 28-vear-old building is being razed to make way for Renaissance II, the second phase of a major redevelopment of the city. Thick smoke billows from the building (center) as more than 1,000 explosive charges do their work. Seven seconds after it began, the demolition is completed (bottom). Construction of a 52-story office building has been proposed in place of the hotel, where former Soviet Premier Khrushchev stayed while visiting the city during his tour of the United States in 1959.</br></br>ROANOKE (UPI)\x89ÛÓIndustry analysts believe recent labor unrest and other problems in Poland, South Africa and Australia may lead foreign coal buyers to depend more heavily on the United States than in recent years.</br></br>Poland\x89Ûªs labor changes, racial unrest in South Africa and a major miners\x89Ûª strike in Australia\x89ÛÓthe world\x89Ûªs three largest coal exporters behind the United States\x89ÛÓare spreading the he-' lief that the United States may be t he most stable source of coal, analysts' said.</br></br>\x89ÛÏThe United States\x89Ûª image as a coal supplier has made a big comeback. Our problems are beginning to pale in com-parispn (with other coal exporters),\x89Û\x9d said Jack Kawa, a coal analyst with. Wheat, First Securities.</br></br>\x89ÛÏThe outlook for I he U.S. export is getting stronger and stronger as the world turns to coal. Customers are turning towards American coal,\x89Û\x9d ho said."

In [157]:
df1[df1['all_text'].str.contains("aadvantag")].all_text

Series([], Name: all_text, dtype: object)

## Text processing

### remove tags

In [158]:
from bs4 import BeautifulSoup
def remove_tags(text):
    cleantext = BeautifulSoup(text, "lxml").text
    return cleantext

In [159]:
sample_text1 = remove_tags(sample_text)
sample_text1

"Farewell Blast For a Hotel In Pittsburgh A \x89Û÷\x89Û÷controlled implosion\x89Û\x9d (top) begins to crumble the 16-story Carlton House Hotel in downtown Pittsburgh Saturday morning. The 28-vear-old building is being razed to make way for Renaissance II, the second phase of a major redevelopment of the city. Thick smoke billows from the building (center) as more than 1,000 explosive charges do their work. Seven seconds after it began, the demolition is completed (bottom). Construction of a 52-story office building has been proposed in place of the hotel, where former Soviet Premier Khrushchev stayed while visiting the city during his tour of the United States in 1959.ROANOKE (UPI)\x89ÛÓIndustry analysts believe recent labor unrest and other problems in Poland, South Africa and Australia may lead foreign coal buyers to depend more heavily on the United States than in recent years.Poland\x89Ûªs labor changes, racial unrest in South Africa and a major miners\x89Ûª strike in Australia\x89ÛÓthe world\x89Ûªs three largest coal exporters behind the United States\x89ÛÓare spreading the he-' lief that the United States may be t he most stable source of coal, analysts' said.\x89ÛÏThe United States\x89Ûª image as a coal supplier has made a big comeback. Our problems are beginning to pale in com-parispn (with other coal exporters),\x89Û\x9d said Jack Kawa, a coal analyst with. Wheat, First Securities.\x89ÛÏThe outlook for I he U.S. export is getting stronger and stronger as the world turns to coal. Customers are turning towards American coal,\x89Û\x9d ho said."

### expand contractions
- contaractions are words that are clubbed together in natural english, e.g. wouldn't, it's etc.
- for our text, the punctuations used in contractions (like single quote) do not show up as it is.
- I looked up the data to recognize these patterns and substitute them with valid puctuations

In [160]:
import re
def process_single_quote(text):
    text = text.replace('\x89Ûª', '\'')
    return text
    
sample_text2 = process_single_quote(sample_text1)
# sample_text1.replace('‰Ûª', '\'')
# sample_text2 = re.sub(r"\x89Ûª", "'", sample_text1)
sample_text2

"Farewell Blast For a Hotel In Pittsburgh A \x89Û÷\x89Û÷controlled implosion\x89Û\x9d (top) begins to crumble the 16-story Carlton House Hotel in downtown Pittsburgh Saturday morning. The 28-vear-old building is being razed to make way for Renaissance II, the second phase of a major redevelopment of the city. Thick smoke billows from the building (center) as more than 1,000 explosive charges do their work. Seven seconds after it began, the demolition is completed (bottom). Construction of a 52-story office building has been proposed in place of the hotel, where former Soviet Premier Khrushchev stayed while visiting the city during his tour of the United States in 1959.ROANOKE (UPI)\x89ÛÓIndustry analysts believe recent labor unrest and other problems in Poland, South Africa and Australia may lead foreign coal buyers to depend more heavily on the United States than in recent years.Poland's labor changes, racial unrest in South Africa and a major miners' strike in Australia\x89ÛÓthe world's three largest coal exporters behind the United States\x89ÛÓare spreading the he-' lief that the United States may be t he most stable source of coal, analysts' said.\x89ÛÏThe United States' image as a coal supplier has made a big comeback. Our problems are beginning to pale in com-parispn (with other coal exporters),\x89Û\x9d said Jack Kawa, a coal analyst with. Wheat, First Securities.\x89ÛÏThe outlook for I he U.S. export is getting stronger and stronger as the world turns to coal. Customers are turning towards American coal,\x89Û\x9d ho said."

In [161]:
import re

def decontract(phrase):
    # specific
    phrase = re.sub(r"won\'t", "would not", phrase)
    phrase = re.sub(r"can\'t", "can not", phrase)

    # general
    phrase = re.sub(r"n\'t", " not", phrase)
    phrase = re.sub(r"\'re", " are", phrase)
    phrase = re.sub(r"\'s", " is", phrase)
    phrase = re.sub(r"\'d", " would", phrase)
    phrase = re.sub(r"\'ll", " will", phrase)
    phrase = re.sub(r"\'t", " not", phrase)
    phrase = re.sub(r"\'ve", " have", phrase)
    phrase = re.sub(r"\'m", " am", phrase)
    return phrase

In [162]:
sample_text3 = decontract(sample_text2)
sample_text3

"Farewell Blast For a Hotel In Pittsburgh A \x89Û÷\x89Û÷controlled implosion\x89Û\x9d (top) begins to crumble the 16-story Carlton House Hotel in downtown Pittsburgh Saturday morning. The 28-vear-old building is being razed to make way for Renaissance II, the second phase of a major redevelopment of the city. Thick smoke billows from the building (center) as more than 1,000 explosive charges do their work. Seven seconds after it began, the demolition is completed (bottom). Construction of a 52-story office building has been proposed in place of the hotel, where former Soviet Premier Khrushchev stayed while visiting the city during his tour of the United States in 1959.ROANOKE (UPI)\x89ÛÓIndustry analysts believe recent labor unrest and other problems in Poland, South Africa and Australia may lead foreign coal buyers to depend more heavily on the United States than in recent years.Poland is labor changes, racial unrest in South Africa and a major miners' strike in Australia\x89ÛÓthe world is three largest coal exporters behind the United States\x89ÛÓare spreading the he-' lief that the United States may be t he most stable source of coal, analysts' said.\x89ÛÏThe United States' image as a coal supplier has made a big comeback. Our problems are beginning to pale in com-parispn (with other coal exporters),\x89Û\x9d said Jack Kawa, a coal analyst with. Wheat, First Securities.\x89ÛÏThe outlook for I he U.S. export is getting stronger and stronger as the world turns to coal. Customers are turning towards American coal,\x89Û\x9d ho said."

### remove special characters: ÛªÓåÈ‰Ï÷ÐÊ¢~å¤|^Ç*]{(ª¨>(

In [163]:
def remove_special_chars(text):
#     special_chars = ['\x89Û÷','\x89Û','\x9d','\x89ÛÓ','\x89ÛÏ','‰Û¢','‰ÛÓ','‰Ûª','åÇ‰ÐÊ åÈ ‰ÛÏ']
    text = re.sub('[ÛªÓåÈ‰Ï÷ÐÊ¢~å¤|^Ç*\]{ª¨>\(\)]', ' ', text)
    text = re.sub('\x89',' ', text)
    text = re.sub('\x9d',' ', text)
    return text

In [164]:
sample_text4 = remove_special_chars(sample_text3)
sample_text4

"Farewell Blast For a Hotel In Pittsburgh A       controlled implosion     top  begins to crumble the 16-story Carlton House Hotel in downtown Pittsburgh Saturday morning. The 28-vear-old building is being razed to make way for Renaissance II, the second phase of a major redevelopment of the city. Thick smoke billows from the building  center  as more than 1,000 explosive charges do their work. Seven seconds after it began, the demolition is completed  bottom . Construction of a 52-story office building has been proposed in place of the hotel, where former Soviet Premier Khrushchev stayed while visiting the city during his tour of the United States in 1959.ROANOKE  UPI    Industry analysts believe recent labor unrest and other problems in Poland, South Africa and Australia may lead foreign coal buyers to depend more heavily on the United States than in recent years.Poland is labor changes, racial unrest in South Africa and a major miners' strike in Australia   the world is three largest coal exporters behind the United States   are spreading the he-' lief that the United States may be t he most stable source of coal, analysts' said.   The United States' image as a coal supplier has made a big comeback. Our problems are beginning to pale in com-parispn  with other coal exporters ,    said Jack Kawa, a coal analyst with. Wheat, First Securities.   The outlook for I he U.S. export is getting stronger and stronger as the world turns to coal. Customers are turning towards American coal,    ho said."

### remove punctuation

In [165]:
import string
import re

punctuation = string.punctuation
def remove_punctuation(text):
#     return text.translate(str.maketrans(' ', ' ', string.punctuation))
#     translator = re.compile('[%s]' % re.escape(string.punctuation))
#     translator.sub(' ', text)
#     re.sub(punctuation, " ", text)
    return re.sub(r'[^a-zA-Z]',' ',text)
#     return text

In [166]:
punctuation = string.punctuation
punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [167]:
remove_punctuation(sample_text)

'Farewell Blast For a Hotel In Pittsburgh A       controlled implosion     top  begins to crumble the    story Carlton House Hotel in downtown Pittsburgh Saturday morning  The    vear old building is being razed to make way for Renaissance II  the second phase of a major redevelopment of the city  Thick smoke billows from the building  center  as more than       explosive charges do their work  Seven seconds after it began  the demolition is completed  bottom   Construction of a    story office building has been proposed in place of the hotel  where former Soviet Premier Khrushchev stayed while visiting the city during his tour of the United States in        br   br ROANOKE  UPI    Industry analysts believe recent labor unrest and other problems in Poland  South Africa and Australia may lead foreign coal buyers to depend more heavily on the United States than in recent years   br   br Poland   s labor changes  racial unrest in South Africa and a major miners    strike in Australia   the world   s three largest coal exporters behind the United States   are spreading the he   lief that the United States may be t he most stable source of coal  analysts  said   br   br    The United States    image as a coal supplier has made a big comeback  Our problems are beginning to pale in com parispn  with other coal exporters      said Jack Kawa  a coal analyst with  Wheat  First Securities   br   br    The outlook for I he U S  export is getting stronger and stronger as the world turns to coal  Customers are turning towards American coal     ho said '

In [168]:
# sample_text4 = remove_punctuation(sample_text3)
# sample_text4

### remove numbers

In [169]:
# we don't require numbers or other figures
def isNumber(token):
    result = token.isnumeric()
    return result

### remove more than 1 space

In [170]:
def remove_more_than_single_space(text):
    return ' '.join(text.split())

In [172]:
sample_text5 = remove_more_than_single_space(sample_text4)
sample_text5

"Farewell Blast For a Hotel In Pittsburgh A controlled implosion top begins to crumble the 16-story Carlton House Hotel in downtown Pittsburgh Saturday morning. The 28-vear-old building is being razed to make way for Renaissance II, the second phase of a major redevelopment of the city. Thick smoke billows from the building center as more than 1,000 explosive charges do their work. Seven seconds after it began, the demolition is completed bottom . Construction of a 52-story office building has been proposed in place of the hotel, where former Soviet Premier Khrushchev stayed while visiting the city during his tour of the United States in 1959.ROANOKE UPI Industry analysts believe recent labor unrest and other problems in Poland, South Africa and Australia may lead foreign coal buyers to depend more heavily on the United States than in recent years.Poland is labor changes, racial unrest in South Africa and a major miners' strike in Australia the world is three largest coal exporters behind the United States are spreading the he-' lief that the United States may be t he most stable source of coal, analysts' said. The United States' image as a coal supplier has made a big comeback. Our problems are beginning to pale in com-parispn with other coal exporters , said Jack Kawa, a coal analyst with. Wheat, First Securities. The outlook for I he U.S. export is getting stronger and stronger as the world turns to coal. Customers are turning towards American coal, ho said."

### stem text

In [173]:
import nltk
nltk.download('punkt')

from nltk.stem import PorterStemmer
from nltk import word_tokenize


stemmer = PorterStemmer()
stem_word_dict = dict()

def stem_token(token):
    stemmed_token = stemmer.stem(token)
    stem_word_dict[stemmed_token] = token
    return stemmed_token

def stem_sentence(text):
#     text2 = remove_tags(text) # tags must be removed first, so that punctuation is not removed
#     text3 = remove_punctuation(text2)
    tokens = word_tokenize(text) 
#     stemmed_tokens = [stem_token(token) for token in tokens if not isNumber(token)] # skip numbers
    tokens = [token for token in tokens if (not isNumber(token) and token!='.' and token!=',') ] # filter numbers, periods
    stemmed_tokens = [stem_token(token) for token in tokens] # if not (isNumber(token) and token=='.' and token==',')]
    stemmed_sentence = ' '.join(stemmed_tokens)
    return stemmed_sentence

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\amita_shukla\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [174]:
sample_text6 = stem_sentence(sample_text5)
sample_text6

"farewel blast for a hotel In pittsburgh A control implos top begin to crumbl the 16-stori carlton hous hotel in downtown pittsburgh saturday morn the 28-vear-old build is be raze to make way for renaiss II the second phase of a major redevelop of the citi thick smoke billow from the build center as more than 1,000 explos charg do their work seven second after it began the demolit is complet bottom construct of a 52-stori offic build ha been propos in place of the hotel where former soviet premier khrushchev stay while visit the citi dure hi tour of the unit state in 1959.roanok upi industri analyst believ recent labor unrest and other problem in poland south africa and australia may lead foreign coal buyer to depend more heavili on the unit state than in recent years.poland is labor chang racial unrest in south africa and a major miner ' strike in australia the world is three largest coal export behind the unit state are spread the he- ' lief that the unit state may be t he most stabl sourc of coal analyst ' said the unit state ' imag as a coal supplier ha made a big comeback our problem are begin to pale in com-parispn with other coal export said jack kawa a coal analyst with wheat first secur the outlook for I he u.s. export is get stronger and stronger as the world turn to coal custom are turn toward american coal ho said"

In [188]:
list = [',','1990','abc','.','abcdefg','1,000']
tokens = [token for token in list if (not isNumber(token) and token!='.' and token!=',') ]
tokens

['abc', 'abcdefg', '1,000']

In [175]:
word_tokenize("u.s.a.")

['u.s.a', '.']

In [176]:
"."!='.'

False

In [177]:
sample_text

"Farewell Blast For a Hotel In Pittsburgh A \x89Û÷\x89Û÷controlled implosion\x89Û\x9d (top) begins to crumble the 16-story Carlton House Hotel in downtown Pittsburgh Saturday morning. The 28-vear-old building is being razed to make way for Renaissance II, the second phase of a major redevelopment of the city. Thick smoke billows from the building (center) as more than 1,000 explosive charges do their work. Seven seconds after it began, the demolition is completed (bottom). Construction of a 52-story office building has been proposed in place of the hotel, where former Soviet Premier Khrushchev stayed while visiting the city during his tour of the United States in 1959.</br></br>ROANOKE (UPI)\x89ÛÓIndustry analysts believe recent labor unrest and other problems in Poland, South Africa and Australia may lead foreign coal buyers to depend more heavily on the United States than in recent years.</br></br>Poland\x89Ûªs labor changes, racial unrest in South Africa and a major miners\x89Ûª strike in Australia\x89ÛÓthe world\x89Ûªs three largest coal exporters behind the United States\x89ÛÓare spreading the he-' lief that the United States may be t he most stable source of coal, analysts' said.</br></br>\x89ÛÏThe United States\x89Ûª image as a coal supplier has made a big comeback. Our problems are beginning to pale in com-parispn (with other coal exporters),\x89Û\x9d said Jack Kawa, a coal analyst with. Wheat, First Securities.</br></br>\x89ÛÏThe outlook for I he U.S. export is getting stronger and stronger as the world turns to coal. Customers are turning towards American coal,\x89Û\x9d ho said."

In [189]:
word_tokenize(sample_text5)

['Farewell',
 'Blast',
 'For',
 'a',
 'Hotel',
 'In',
 'Pittsburgh',
 'A',
 'controlled',
 'implosion',
 'top',
 'begins',
 'to',
 'crumble',
 'the',
 '16-story',
 'Carlton',
 'House',
 'Hotel',
 'in',
 'downtown',
 'Pittsburgh',
 'Saturday',
 'morning',
 '.',
 'The',
 '28-vear-old',
 'building',
 'is',
 'being',
 'razed',
 'to',
 'make',
 'way',
 'for',
 'Renaissance',
 'II',
 ',',
 'the',
 'second',
 'phase',
 'of',
 'a',
 'major',
 'redevelopment',
 'of',
 'the',
 'city',
 '.',
 'Thick',
 'smoke',
 'billows',
 'from',
 'the',
 'building',
 'center',
 'as',
 'more',
 'than',
 '1,000',
 'explosive',
 'charges',
 'do',
 'their',
 'work',
 '.',
 'Seven',
 'seconds',
 'after',
 'it',
 'began',
 ',',
 'the',
 'demolition',
 'is',
 'completed',
 'bottom',
 '.',
 'Construction',
 'of',
 'a',
 '52-story',
 'office',
 'building',
 'has',
 'been',
 'proposed',
 'in',
 'place',
 'of',
 'the',
 'hotel',
 ',',
 'where',
 'former',
 'Soviet',
 'Premier',
 'Khrushchev',
 'stayed',
 'while',
 'visiting',
 'the',
 'city',
 'during',
 'his',
 'tour',
 'of',
 'the',
 'United',
 'States',
 'in',
 '1959.ROANOKE',
 'UPI',
 'Industry',
 'analysts',
 'believe',
 'recent',
 'labor',
 'unrest',
 'and',
 'other',
 'problems',
 'in',
 'Poland',
 ',',
 'South',
 'Africa',
 'and',
 'Australia',
 'may',
 'lead',
 'foreign',
 'coal',
 'buyers',
 'to',
 'depend',
 'more',
 'heavily',
 'on',
 'the',
 'United',
 'States',
 'than',
 'in',
 'recent',
 'years.Poland',
 'is',
 'labor',
 'changes',
 ',',
 'racial',
 'unrest',
 'in',
 'South',
 'Africa',
 'and',
 'a',
 'major',
 'miners',
 "'",
 'strike',
 'in',
 'Australia',
 'the',
 'world',
 'is',
 'three',
 'largest',
 'coal',
 'exporters',
 'behind',
 'the',
 'United',
 'States',
 'are',
 'spreading',
 'the',
 'he-',
 "'",
 'lief',
 'that',
 'the',
 'United',
 'States',
 'may',
 'be',
 't',
 'he',
 'most',
 'stable',
 'source',
 'of',
 'coal',
 ',',
 'analysts',
 "'",
 'said',
 '.',
 'The',
 'United',
 'States',
 "'",
 'image',
 'as',
 'a',
 'coal',
 'supplier',
 'has',
 'made',
 'a',
 'big',
 'comeback',
 '.',
 'Our',
 'problems',
 'are',
 'beginning',
 'to',
 'pale',
 'in',
 'com-parispn',
 'with',
 'other',
 'coal',
 'exporters',
 ',',
 'said',
 'Jack',
 'Kawa',
 ',',
 'a',
 'coal',
 'analyst',
 'with',
 '.',
 'Wheat',
 ',',
 'First',
 'Securities',
 '.',
 'The',
 'outlook',
 'for',
 'I',
 'he',
 'U.S.',
 'export',
 'is',
 'getting',
 'stronger',
 'and',
 'stronger',
 'as',
 'the',
 'world',
 'turns',
 'to',
 'coal',
 '.',
 'Customers',
 'are',
 'turning',
 'towards',
 'American',
 'coal',
 ',',
 'ho',
 'said',
 '.']

In [191]:
stem_token('1959.RENOKE')

'1959.renok'

In [179]:
a = dict()
a['a'] = 'b'
a

{'a': 'b'}

### leammatize text

In [180]:
import nltk
nltk.download('wordnet')

from nltk.stem import WordNetLemmatizer
from nltk import word_tokenize

wnl = WordNetLemmatizer()

def lemmatize_sentence(text):
    tokens = word_tokenize(text)
    lemmatized_tokens = [wnl.lemmatize(token) for token in tokens if not (isNumber(token) and token!='.' and token!=',')]
    lemmatized_sentence = ' '.join(lemmatized_tokens)
    return lemmatized_sentence

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\amita_shukla\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

### run all processing

In [181]:
def process_all(text):
    text = remove_tags(text)
    text = process_single_quote(text)
    text = decontract(text)
    text = remove_special_chars(text)
#     text = remove_punctuation(text)
    text = remove_more_than_single_space(text)
    text = text.lower()
    text = stem_sentence(text)
#     text = lemmatize_sentence(text)
    return text

In [182]:
# df2 = df1['all_text'].apply(stem_sentence)
df1.loc[:,'all_text'] = df1['all_text'].apply(process_all)
df1

,headline,text,relevance,relevance_point,all_text
0,Yields on CDs Fell in the Latest Week,NEW YORK -- Yields on most certificates of dep...,yes,1,yield on cd fell in the latest week new york -...
1,The Morning Brief: White House Seeks to Limit ...,The Wall Street Journal Online</br></br>The Mo...,no,0,the morn brief : white hous seek to limit chil...
2,Banking Bill Negotiators Set Compromise --- Pl...,WASHINGTON -- In an effort to achieve banking ...,no,0,bank bill negoti set compromis -- - plan to wi...
3,Manager's Journal: Sniffing Out Drug Abusers I...,The statistics on the enormous costs of employ...,no,0,manag is journal : snif out drug abus is no qu...
4,Currency Trading: Dollar Remains in Tight Rang...,NEW YORK -- Indecision marked the dollar's ton...,yes,1,currenc trade : dollar remain in tight rang am...
...,...,...,...,...,...
7986,"Sawyer Sees Strong Economy For 2 Years, Truce ...",Secretary of Commerce Charles W. Sawyer said y...,yes,1,sawyer see strong economi for year truce or no...
7987,Oil's losses are airlines' gains,"U.S. stocks inched up last week, overcoming co...",no,0,oil is loss are airlin ' gain u.s. stock inch ...
7988,Full Senate to vote on Bernanke; PANEL ADVANCE...,Ben S. Bernanke cleared a key hurdle Thursday ...,no,0,full senat to vote on bernank ; panel advanc r...
7989,Reinventing Opportunities,The White House's push to contract out many fe...,no,0,reinvent opportun the white hous is push to co...
7990,Stocks Rise On News of Auto Output: Dow Climbs...,NEW YORK. April 17-Automobile stocks put on th...,no,0,stock rise on news of auto output : dow climb ...

In [88]:
# print(df1.loc[1:20,'all_text']) # before

In [89]:
# print(df1.loc[1:20,'all_text']) # after

In [183]:
sample_text

"Farewell Blast For a Hotel In Pittsburgh A \x89Û÷\x89Û÷controlled implosion\x89Û\x9d (top) begins to crumble the 16-story Carlton House Hotel in downtown Pittsburgh Saturday morning. The 28-vear-old building is being razed to make way for Renaissance II, the second phase of a major redevelopment of the city. Thick smoke billows from the building (center) as more than 1,000 explosive charges do their work. Seven seconds after it began, the demolition is completed (bottom). Construction of a 52-story office building has been proposed in place of the hotel, where former Soviet Premier Khrushchev stayed while visiting the city during his tour of the United States in 1959.</br></br>ROANOKE (UPI)\x89ÛÓIndustry analysts believe recent labor unrest and other problems in Poland, South Africa and Australia may lead foreign coal buyers to depend more heavily on the United States than in recent years.</br></br>Poland\x89Ûªs labor changes, racial unrest in South Africa and a major miners\x89Ûª strike in Australia\x89ÛÓthe world\x89Ûªs three largest coal exporters behind the United States\x89ÛÓare spreading the he-' lief that the United States may be t he most stable source of coal, analysts' said.</br></br>\x89ÛÏThe United States\x89Ûª image as a coal supplier has made a big comeback. Our problems are beginning to pale in com-parispn (with other coal exporters),\x89Û\x9d said Jack Kawa, a coal analyst with. Wheat, First Securities.</br></br>\x89ÛÏThe outlook for I he U.S. export is getting stronger and stronger as the world turns to coal. Customers are turning towards American coal,\x89Û\x9d ho said."

In [184]:
df1.loc[4016,'all_text'] # with stemming # DO NOT RUN THIS CELL

"farewel blast for a hotel in pittsburgh a control implos top begin to crumbl the 16-stori carlton hous hotel in downtown pittsburgh saturday morn the 28-vear-old build is be raze to make way for renaiss ii the second phase of a major redevelop of the citi thick smoke billow from the build center as more than 1,000 explos charg do their work seven second after it began the demolit is complet bottom construct of a 52-stori offic build ha been propos in place of the hotel where former soviet premier khrushchev stay while visit the citi dure hi tour of the unit state in 1959.roanok upi industri analyst believ recent labor unrest and other problem in poland south africa and australia may lead foreign coal buyer to depend more heavili on the unit state than in recent years.poland is labor chang racial unrest in south africa and a major miner ' strike in australia the world is three largest coal export behind the unit state are spread the he- ' lief that the unit state may be t he most stabl sourc of coal analyst ' said the unit state ' imag as a coal supplier ha made a big comeback our problem are begin to pale in com-parispn with other coal export said jack kawa a coal analyst with wheat first secur the outlook for i he u.s. export is get stronger and stronger as the world turn to coal custom are turn toward american coal ho said"

In [158]:
df1.loc[4008,'all_text'] # with lemmatization # DO NOT RUN THIS CELL

'when number are unproduct conflict survey illustr danger of misread econom data busi product is one of those number polici wonk throw around when they talk about the economi if worker produc more in the same amount of time the economi can grow more so the labor depart is report yesterday that product of u s busi fell percent in the three month end in june sound like bad news if it is accur the labor depart attribut the declin to increas in hour work and in the number of peopl work as reveal by it survey of employ but the depart is survey of household show that the number of peopl work ha grown about one sixth as much as the employ survey say and if the household survey is right then the work forc ha not grown as much and product probabl ha not fallen as much which is better news for the economi it is not easi to get a handl on precis what is happen in an economi undergo big chang in what busi produc how well they produc it and whom they hire to produc it relianc on ani one statist may lead to misjudg the height of the forest base on one misshapen tree pay too much attent to econom indic that do not tell the whole stori can skew polici accord to robert brusca chief economist at nikko secur co intern in new york if wage are rise but product is fall which is what the payrol survey suggest is happen then inflat loom'

## Vectorize Text

In [185]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(stop_words='english', max_features= 1000)
x = vectorizer.fit_transform(df1['all_text'])
x
# arr = x.toarray()
# arr

<7991x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 532548 stored elements in Compressed Sparse Row format>

In [78]:
# x.shape # before

(7991, 44911)

In [184]:
x.shape #after # with lemmatizer. hmmm more number of columns than stemming

(7991, 1000)

In [186]:
x.shape # after # with stemming.

(7991, 1000)

In [187]:
# vectorizer.get_feature_names()[42050:42060]
features = vectorizer.get_feature_names()
# features[24000:26000]
features

['000',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '1980',
 '1990',
 '20',
 '21',
 '22',
 '25',
 '30',
 '32',
 '40',
 '50',
 '500',
 '60',
 '75',
 'abl',
 'abov',
 'acceler',
 'accept',
 'accord',
 'account',
 'act',
 'action',
 'activ',
 'actual',
 'ad',
 'add',
 'addit',
 'adjust',
 'administr',
 'advanc',
 'advis',
 'affect',
 'afternoon',
 'age',
 'agenc',
 'ago',
 'agre',
 'agreement',
 'ahead',
 'aid',
 'aim',
 'air',
 'airlin',
 'alan',
 'allow',
 'alreadi',
 'alway',
 'america',
 'american',
 'amid',
 'analysi',
 'analyst',
 'ani',
 'announc',
 'annual',
 'anoth',
 'answer',
 'anti',
 'anticip',
 'anyth',
 'ap',
 'appar',
 'appear',
 'approach',
 'approv',
 'april',
 'area',
 'argu',
 'asia',
 'asian',
 'ask',
 'asset',
 'assist',
 'associ',
 'attack',
 'attempt',
 'attent',
 'attract',
 'auction',
 'aug',
 'august',
 'author',
 'auto',
 'avail',
 'averag',
 'avoid',
 'away',
 'bad',
 'balanc',
 'bank',
 'banker',
 'bankruptci',
 'bas',
 'base',
 'basi',
 'basic',
 'bear',
 'becaus',
 'becom',
 'befor',
 'began',
 'begin',
 'believ',
 'benchmark',
 'benefit',
 'bernank',
 'best',
 'bet',
 'better',
 'bid',
 'big',
 'biggest',
 'billion',
 'bit',
 'black',
 'blame',
 'blue',
 'board',
 'bond',
 'book',
 'boom',
 'boost',
 'borrow',
 'boston',
 'break',
 'bring',
 'broad',
 'broader',
 'broker',
 'brought',
 'budget',
 'build',
 'bureau',
 'bush',
 'busi',
 'buy',
 'buyer',
 'california',
 'came',
 'campaign',
 'canada',
 'canadian',
 'candid',
 'cap',
 'capit',
 'car',
 'card',
 'care',
 'carri',
 'carter',
 'case',
 'cash',
 'caus',
 'cent',
 'center',
 'central',
 'certain',
 'chairman',
 'challeng',
 'chanc',
 'chang',
 'charg',
 'check',
 'chicago',
 'chief',
 'children',
 'china',
 'chines',
 'chip',
 'cite',
 'citi',
 'claim',
 'class',
 'clear',
 'client',
 'climb',
 'clinton',
 'close',
 'collaps',
 'collect',
 'colleg',
 'com',
 'combin',
 'come',
 'comment',
 'commerc',
 'commerci',
 'commiss',
 'commit',
 'committe',
 'commod',
 'common',
 'commun',
 'compani',
 'compar',
 'competit',
 'complet',
 'composit',
 'comput',
 'concern',
 'condit',
 'confer',
 'confid',
 'confirm',
 'congress',
 'congression',
 'conserv',
 'consid',
 'construct',
 'consult',
 'consum',
 'continu',
 'contract',
 'contribut',
 'control',
 'corp',
 'corpor',
 'correct',
 'cost',
 'council',
 'count',
 'counti',
 'countri',
 'coupl',
 'cours',
 'court',
 'cover',
 'crash',
 'creat',
 'credit',
 'crisi',
 'critic',
 'crude',
 'currenc',
 'current',
 'custom',
 'cut',
 'damag',
 'data',
 'david',
 'day',
 'deal',
 'dealer',
 'debat',
 'debt',
 'dec',
 'decad',
 'decemb',
 'decid',
 'decis',
 'declin',
 'defens',
 'deficit',
 'delay',
 'demand',
 'democrat',
 'depart',
 'depend',
 'deposit',
 'depress',
 'design',
 'despit',
 'determin',
 'develop',
 'did',
 'differ',
 'difficult',
 'dip',
 'direct',
 'director',
 'disappoint',
 'discount',
 'discuss',
 'district',
 'dividend',
 'doe',
 'dollar',
 'domest',
 'doubl',
 'doubt',
 'dow',
 'downturn',
 'drive',
 'drop',
 'drug',
 'dure',
 'earli',
 'earlier',
 'earn',
 'eas',
 'econom',
 'economi',
 'economist',
 'economy',
 'edg',
 'educ',
 'effect',
 'effort',
 'elect',
 'electr',
 'electron',
 'emerg',
 'employ',
 'employe',
 'encourag',
 'end',
 'energi',
 'entir',
 'equip',
 'equiti',
 'especi',
 'estat',
 'estim',
 'euro',
 'europ',
 'european',
 'event',
 'everi',
 'everyth',
 'evid',
 'exampl',
 'exchang',
 'execut',
 'exist',
 'expand',
 'expans',
 'expect',
 'expens',
 'expert',
 'explain',
 'export',
 'express',
 'extend',
 'face',
 'fact',
 'factor',
 'factori',
 'fail',
 'fall',
 'fallen',
 'famili',
 'fanni',
 'far',
 'farm',
 'fast',
 'faster',
 'favor',
 'fear',
 'februari',
 'fed',
 'feder',
 'fee',
 'feel',
 'fell',
 'fight',
 'figur',
 'file',
 'final',
 'financ',
 'financi',
 'finish',
 'firm',
 'fiscal',
 'fix',
 'fixed',
 'flat',
 'flow',
 'focu',
 'focus',
 'follow',
 'food',
 'forc',
 'ford',
 'forecast',
 'foreign',
 'form',
 'fourth',
 'franc',
 'free',
 'friday',
 'fuel',
 'fund',
 'futur',
 'ga',
 'gain',
 'gap',
 'gave',
 'gdp',
 'gener',
 'georg',
 'german',
 'germani',
 'giant',
 'given',
 'global',
 'goal',
 'goe',
 'gold',
 'good',
 'got',
 'govern',
 'governor',
 'great',
 'greater',
 'greenspan',
 'grew',
 'gross',
 'ground',
 'group',
 'grow',
 'growth',
 'ha',
 'half',
 'hand',
 'happen',
 'hard',
 'head',
 'health',
 'hear',
 'heavi',
 'hedg',
 'held',
 'help',
 'hi',
 'high',
 'higher',
 'highest',
 'hire',
 'histor',
 'histori',
 'hit',
 'hold',
 'holiday',
 'home',
 'hope',
 'hour',
 'hous',
 'household',
 'howev',
 'huge',
 'hurt',
 'idea',
 'imf',
 'immedi',
 'impact',
 'import',
 'improv',
 'includ',
 'incom',
 'increas',
 'increasingli',
 'inde',
 'index',
 'indic',
 'individu',
 'industri',
 'inflat',
 'inflation',
 'inflationari',
 'inform',
 'initi',
 'instead',
 'institut',
 'insur',
 'intern',
 'internet',
 'interview',
 'inventori',
 'invest',
 'investig',
 'investor',
 'involv',
 'issu',
 'item',
 'jame',
 'jan',
 'januari',
 'japan',
 'japanes',
 'job',
 'jobless',
 'john',
 'join',
 'jone',
 'journal',
 'juli',
 'jump',
 'june',
 'just',
 'kept',
 'key',
 'kind',
 'know',
 'known',
 'labor',
 'land',
 'larg',
 'larger',
 'largest',
 'late',
 'later',
 'latest',
 'launch',
 'law',
 'lawmak',
 'lead',
 'leader',
 'leav',
 'led',
 'left',
 'legal',
 'legisl',
 'lend',
 'lender',
 'let',
 'level',
 'life',
 'lift',
 'light',
 'like',
 'limit',
 'line',
 'list',
 'littl',
 'live',
 'loan',
 'local',
 'london',
 'long',
 'longer',
 'look',
 'lose',
 'loss',
 'lost',
 'lot',
 'low',
 'lower',
 'lowest',
 'main',
 'maintain',
 'major',
 'make',
 'maker',
 'man',
 'manag',
 'mani',
 'manufactur',
 'march',
 'margin',
 'mark',
 'market',
 'maryland',
 'matter',
 'mean',
 'meanwhil',
 'measur',
 'meet',
 'member',
 'men',
 'mexico',
 'mid',
 'middl',
 'militari',
 'million',
 'mind',
 'minist',
 'minut',
 'mix',
 'moder',
 'modest',
 'monday',
 'monetari',
 'money',
 'month',
 'monthli',
 'morgan',
 'morn',
 'mortgag',
 'mostli',
 'motor',
 'mr',
 'mutual',
 'narrow',
 'nasdaq',
 'nation',
 'natur',
 'near',
 'nearli',
 'need',
 'neg',
 'negoti',
 'net',
 'network',
 'new',
 'news',
 'night',
 'nixon',
 'north',
 'note',
 'noth',
 'novemb',
 'number',
 'obama',
 'oct',
 'octob',
 'offer',
 'offic',
 'offici',
 'offset',
 'oil',
 'old',
 'onc',
 'onli',
 'open',
 'oper',
 'opportun',
 'opposit',
 'option',
 'order',
 'organ',
 'origin',
 'outlook',
 'output',
 'outsid',
 'overal',
 'pace',
 'packag',
 'page',
 'paid',
 'paper',
 'parti',
 'particip',
 'particularli',
 'partner',
 'pass',
 'past',
 'paul',
 'pay',
 'payment',
 'payrol',
 'peak',
 'pension',
 'peopl',
 'percent',
 'percentag',
 'perform',
 'perhap',
 'period',
 'person',
 'pick',
 'pictur',
 'place',
 'plan',
 'plant',
 'play',
 'plung',
 'point',
 'polici',
 'polit',
 'poll',
 'poor',
 'popular',
 'portfolio',
 'posit',
 'possibl',
 'post',
 'potenti',
 'power',
 'practic',
 'predict',
 'prepar',
 'present',
 'presid',
 'presidenti',
 'press',
 'pressur',
 'prevent',
 'previou',
 'pric',
 'price',
 'prime',
 'privat',
 'probabl',
 'problem',
 'process',
 'produc',
 'product',
 'profit',
 'program',
 'progress',
 'project',
 'promis',
 'prompt',
 'properti',
 'propos',
 'prospect',
 'protect',
 'provid',
 'public',
 'publish',
 'pull',
 'purchas',
 'push',
 'quart',
 'quarter',
 'quarterli',
 'question',
 'quickli',
 'quit',
 'rail',
 'rais',
 'ralli',
 'rang',
 'rate',
 'rates',
 'reach',
 'read',
 'reagan',
 'real',
 'realli',
 'reason',
 'rebound',
 'receiv',
 'recent',
 'recess',
 'recession',
 'record',
 'recov',
 'recoveri',
 'reduc',
 'reduct',
 'reflect',
 'reform',
 'region',
 'regul',
 'rel',
 'relat',
 'releas',
 'remain',
 'remark',
 'report',
 'repres',
 'republican',
 'requir',
 'research',
 'reserv',
 'respond',
 'respons',
 'rest',
 'result',
 'retail',
 'retir',
 'return',
 'revenu',
 'revers',
 'review',
 'revis',
 'richard',
 'right',
 'rise',
 'risen',
 'risk',
 'robert',
 'role',
 'room',
 'rose',
 'rule',
 'run',
 'said',
 'sale',
 'san',
 'save',
 'saw',
 'say',
 'schedul',
 'school',
 'season',
 'second',
 'secretari',
 'sector',
 'secur',
 'seek',
 'seen',
 'sell',
 'sen',
 'senat',
 'send',
 'senior',
 'sens',
 'sent',
 'separ',
 'sept',
 'septemb',
 'seri',
 'seriou',
 'serv',
 'servic',
 'session',
 'set',
 'seven',
 'sever',
 'share',
 'sharp',
 'sharpli',
 'shift',
 'shop',
 'short',
 'sign',
 'signal',
 'signific',
 'similar',
 'simpli',
 'sinc',
 'singl',
 'situat',
 'size',
 'slide',
 'slightli',
 'slip',
 'slow',
 'slowdown',
 'slump',
 'small',
 'smaller',
 'soar',
 'social',
 'sold',
 'someth',
 'soon',
 'sourc',
 'south',
 'special',
 'specul',
 'speech',
 'spend',
 'spokesman',
 'spread',
 'spring',
 'spur',
 'stabil',
 'staff',
 'stand',
 'standard',
 'start',
 'state',
 'statement',
 'statist',
 'stay',
 'steadi',
 'steel',
 'step',
 'stimulu',
 'stock',
 'stop',
 'store',
 'stori',
 'straight',
 'strategi',
 'strategist',
 'street',
 'strength',
 'strike',
 'strong',
 'stronger',
 'struggl',
 'student',
 'studi',
 'substanti',
 'success',
 'suffer',
 'suggest',
 'summer',
 'suppli',
 'support',
 'sure',
 'surg',
 'surplu',
 'surpris',
 'survey',
 'sustain',
 'taken',
 'talk',
 'target',
 'tax',
 'taxpay',
 'tech',
 'technolog',
 'tell',
 'tend',
 'term',
 'test',
 'texa',
 'th',
 'themselv',
 'thi',
 'thing',
 'think',
 'thought',
 'threaten',
 'thu',
 'thursday',
 'tie',
 'tighten',
 'tim',
 'time',
 'today',
 'togeth',
 'tokyo',
 'told',
 'took',
 'total',
 'track',
 'trad',
 'trade',
 'trader',
 'tradit',
 'transact',
 'treasuri',
 'trend',
 'tri',
 'trillion',
 'troubl',
 'trust',
 'tuesday',
 'tumbl',
 'turn',
 'typic',
 'uncertainti',
 'unchang',
 'unemploy',
 'union',
 'unit',
 'univers',
 'unlik',
 'unusu',
 'upward',
 'urg',
 'use',
 'usual',
 'util',
 'valu',
 'veri',
 'vice',
 'view',
 'virginia',
 'volatil',
 'volcker',
 'volum',
 'vote',
 'voter',
 'wa',
 'wage',
 'wait',
 'wall',
 'want',
 'war',
 'warn',
 'washington',
 'watch',
 'way',
 'weak',
 'weaken',
 'wednesday',
 'week',
 'weekend',
 'weekli',
 'went',
 'west',
 'whi',
 'whil',
 'white',
 'wide',
 'william',
 'win',
 'women',
 'word',
 'work',
 'worker',
 'world',
 'worri',
 'wors',
 'worst',
 'worth',
 'write',
 'year',
 'years',
 'yen',
 'yesterday',
 'yield',
 'york']

In [190]:
[print(feature + " : " + stem_word_dict[feature] ) for feature in features]

KeyError: '000'

In [189]:
# news_df.loc[:,['text_vec']] = list(arr)
# news_df['text_vec'] = list(arr)
df1.loc[:,'text_vec'] = list(x)
df1

,headline,text,relevance,relevance_point,all_text,text_vec
0,Yields on CDs Fell in the Latest Week,NEW YORK -- Yields on most certificates of dep...,yes,1,yield on cd fell in the latest week new york y...,"(0, 675)\t0.09365599515159433\n (0, 67)\t0...."
1,The Morning Brief: White House Seeks to Limit ...,The Wall Street Journal Online</br></br>The Mo...,no,0,the morn brief white hous seek to limit child ...,"(0, 134)\t0.03921864701416703\n (0, 740)\t0..."
2,Banking Bill Negotiators Set Compromise --- Pl...,WASHINGTON -- In an effort to achieve banking ...,no,0,bank bill negoti set compromis plan to widen b...,"(0, 90)\t0.05644356595962317\n (0, 473)\t0...."
3,Manager's Journal: Sniffing Out Drug Abusers I...,The statistics on the enormous costs of employ...,no,0,manag is journal snif out drug abus is no quic...,"(0, 416)\t0.022796348097483154\n (0, 873)\t..."
4,Currency Trading: Dollar Remains in Tight Rang...,NEW YORK -- Indecision marked the dollar's ton...,yes,1,currenc trade dollar remain in tight rang amid...,"(0, 27)\t0.07884541027775498\n (0, 724)\t0...."
...,...,...,...,...,...,...
7986,"Sawyer Sees Strong Economy For 2 Years, Truce ...",Secretary of Commerce Charles W. Sawyer said y...,yes,1,sawyer see strong economi for year truce or no...,"(0, 243)\t0.2891002978217384\n (0, 0)\t0.14..."
7987,Oil's losses are airlines' gains,"U.S. stocks inched up last week, overcoming co...",no,0,oil is loss are airlin gain u s stock inch up ...,"(0, 93)\t0.12221526386293342\n (0, 30)\t0.1..."
7988,Full Senate to vote on Bernanke; PANEL ADVANCE...,Ben S. Bernanke cleared a key hurdle Thursday ...,no,0,full senat to vote on bernank panel advanc ren...,"(0, 955)\t0.06442821769706356\n (0, 273)\t0..."
7989,Reinventing Opportunities,The White House's push to contract out many fe...,no,0,reinvent opportun the white hous is push to co...,"(0, 669)\t0.10125311592551942\n (0, 22)\t0...."
7990,Stocks Rise On News of Auto Output: Dow Climbs...,NEW YORK. April 17-Automobile stocks put on th...,no,0,stock rise on news of auto output dow climb po...,"(0, 0)\t0.11290892678399932\n (0, 866)\t0.1..."

In [190]:
df1.shape

(7991, 6)

In [191]:
df2 = pd.DataFrame(x.toarray(), columns=vectorizer.get_feature_names())
df2

,abl,abov,acceler,accept,accord,account,achiev,acquir,act,action,...,worst,worth,write,wrong,year,yen,yesterday,yield,york,zero
0,0.000000,0.000000,0.0,0.0,0.143248,0.0,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.037099,0.000000,0.060151,0.451279,0.117518,0.0
1,0.000000,0.045158,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.017583,0.000000,0.000000,0.000000,0.055699,0.0
2,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.076296,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
3,0.000000,0.000000,0.0,0.0,0.025669,0.0,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.039886,0.000000,0.000000,0.000000,0.000000,0.0
4,0.000000,0.084756,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.000000,0.491469,0.053508,0.000000,0.209080,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,0.145532,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.149060,0.000000,0.080560,0.000000,0.078697,0.0
7987,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.036754,0.000000,0.000000,0.000000,0.000000,0.0
7988,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.048461,0.044513,...,0.000000,0.0,0.0,0.0,0.017877,0.000000,0.000000,0.000000,0.000000,0.0
7989,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.035570,0.000000,0.000000,0.000000,0.000000,0.0
7990,0.112909,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,...,0.113694,0.0,0.0,0.0,0.038549,0.000000,0.000000,0.000000,0.061056,0.0

In [192]:
res = pd.concat([df1, df2], axis=1)
res

,headline,text,relevance,relevance_point,all_text,text_vec,abl,abov,acceler,accept,...,worst,worth,write,wrong,year,yen,yesterday,yield,york,zero
0,Yields on CDs Fell in the Latest Week,NEW YORK -- Yields on most certificates of dep...,yes,1,yield on cd fell in the latest week new york y...,"(0, 675)\t0.09365599515159433\n (0, 67)\t0....",0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.037099,0.000000,0.060151,0.451279,0.117518,0.0
1,The Morning Brief: White House Seeks to Limit ...,The Wall Street Journal Online</br></br>The Mo...,no,0,the morn brief white hous seek to limit child ...,"(0, 134)\t0.03921864701416703\n (0, 740)\t0...",0.000000,0.045158,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.017583,0.000000,0.000000,0.000000,0.055699,0.0
2,Banking Bill Negotiators Set Compromise --- Pl...,WASHINGTON -- In an effort to achieve banking ...,no,0,bank bill negoti set compromis plan to widen b...,"(0, 90)\t0.05644356595962317\n (0, 473)\t0....",0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
3,Manager's Journal: Sniffing Out Drug Abusers I...,The statistics on the enormous costs of employ...,no,0,manag is journal snif out drug abus is no quic...,"(0, 416)\t0.022796348097483154\n (0, 873)\t...",0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.039886,0.000000,0.000000,0.000000,0.000000,0.0
4,Currency Trading: Dollar Remains in Tight Rang...,NEW YORK -- Indecision marked the dollar's ton...,yes,1,currenc trade dollar remain in tight rang amid...,"(0, 27)\t0.07884541027775498\n (0, 724)\t0....",0.000000,0.084756,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.491469,0.053508,0.000000,0.209080,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,"Sawyer Sees Strong Economy For 2 Years, Truce ...",Secretary of Commerce Charles W. Sawyer said y...,yes,1,sawyer see strong economi for year truce or no...,"(0, 243)\t0.2891002978217384\n (0, 0)\t0.14...",0.145532,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.149060,0.000000,0.080560,0.000000,0.078697,0.0
7987,Oil's losses are airlines' gains,"U.S. stocks inched up last week, overcoming co...",no,0,oil is loss are airlin gain u s stock inch up ...,"(0, 93)\t0.12221526386293342\n (0, 30)\t0.1...",0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.036754,0.000000,0.000000,0.000000,0.000000,0.0
7988,Full Senate to vote on Bernanke; PANEL ADVANCE...,Ben S. Bernanke cleared a key hurdle Thursday ...,no,0,full senat to vote on bernank panel advanc ren...,"(0, 955)\t0.06442821769706356\n (0, 273)\t0...",0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.017877,0.000000,0.000000,0.000000,0.000000,0.0
7989,Reinventing Opportunities,The White House's push to contract out many fe...,no,0,reinvent opportun the white hous is push to co...,"(0, 669)\t0.10125311592551942\n (0, 22)\t0....",0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.035570,0.000000,0.000000,0.000000,0.000000,0.0
7990,Stocks Rise On News of Auto Output: Dow Climbs...,NEW YORK. April 17-Automobile stocks put on th...,no,0,stock rise on news of auto output dow climb po...,"(0, 0)\t0.11290892678399932\n (0, 866)\t0.1...",0.112909,0.000000,0.0,0.0,...,0.113694,0.0,0.0,0.0,0.038549,0.000000,0.000000,0.000000,0.061056,0.0

In [90]:
res.describe() # don't run this, time-taking

,relevance_point,00,000,000100,000uo,000uoall,000uoi,000uoin,000uoth,000uoto,...,zugby,zuhdi,zurich,zurichuo,zurnlnd,zweig,zweng,zynga,zyuganov,zz
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,...,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,0.178063,0.000873,0.011232,0.000008,0.000030,0.000015,0.000018,0.000021,0.000017,0.000021,...,0.000017,0.000014,0.000174,0.000015,0.000008,0.000014,0.000027,0.000013,0.000012,0.000027
std,0.382221,0.009433,0.033578,0.000760,0.001902,0.001338,0.001566,0.001840,0.001521,0.001840,...,0.001501,0.001271,0.005461,0.001342,0.000677,0.001249,0.002408,0.001163,0.001060,0.002413
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,0.205453,0.397475,0.067952,0.137307,0.119630,0.140043,0.164556,0.136066,0.164556,...,0.134252,0.113668,0.239804,0.120033,0.060518,0.111700,0.215380,0.103989,0.094776,0.215798

In [193]:
# drop all colummns except term features and target col('relevance')
res.drop(['headline', 'text', 'relevance', 'all_text', 'text_vec'], axis=1, inplace=True)
res

,relevance_point,abl,abov,acceler,accept,accord,account,achiev,acquir,act,...,worst,worth,write,wrong,year,yen,yesterday,yield,york,zero
0,1,0.000000,0.000000,0.0,0.0,0.143248,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.037099,0.000000,0.060151,0.451279,0.117518,0.0
1,0,0.000000,0.045158,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.017583,0.000000,0.000000,0.000000,0.055699,0.0
2,0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.076296,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
3,0,0.000000,0.000000,0.0,0.0,0.025669,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.039886,0.000000,0.000000,0.000000,0.000000,0.0
4,1,0.000000,0.084756,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.000000,0.491469,0.053508,0.000000,0.209080,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,1,0.145532,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.149060,0.000000,0.080560,0.000000,0.078697,0.0
7987,0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.036754,0.000000,0.000000,0.000000,0.000000,0.0
7988,0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.048461,...,0.000000,0.0,0.0,0.0,0.017877,0.000000,0.000000,0.000000,0.000000,0.0
7989,0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.035570,0.000000,0.000000,0.000000,0.000000,0.0
7990,0,0.112909,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.113694,0.0,0.0,0.0,0.038549,0.000000,0.000000,0.000000,0.061056,0.0

-- ## Vectorize Headline

In [27]:
# vectorizer2 = TfidfVectorizer()
# x2 = vectorizer2.fit_transform(news_df['headline'])
# x2

In [28]:
# len(list(x2))

In [29]:
# vectorizer2.get_feature_names()

In [194]:
res

,relevance_point,abl,abov,acceler,accept,accord,account,achiev,acquir,act,...,worst,worth,write,wrong,year,yen,yesterday,yield,york,zero
0,1,0.000000,0.000000,0.0,0.0,0.143248,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.037099,0.000000,0.060151,0.451279,0.117518,0.0
1,0,0.000000,0.045158,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.017583,0.000000,0.000000,0.000000,0.055699,0.0
2,0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.076296,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
3,0,0.000000,0.000000,0.0,0.0,0.025669,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.039886,0.000000,0.000000,0.000000,0.000000,0.0
4,1,0.000000,0.084756,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.000000,0.491469,0.053508,0.000000,0.209080,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,1,0.145532,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.149060,0.000000,0.080560,0.000000,0.078697,0.0
7987,0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.036754,0.000000,0.000000,0.000000,0.000000,0.0
7988,0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.048461,...,0.000000,0.0,0.0,0.0,0.017877,0.000000,0.000000,0.000000,0.000000,0.0
7989,0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.035570,0.000000,0.000000,0.000000,0.000000,0.0
7990,0,0.112909,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.113694,0.0,0.0,0.0,0.038549,0.000000,0.000000,0.000000,0.061056,0.0

In [26]:
# news_df.loc[:,'headline_vec'] = x2

## feature-target split

In [195]:
target_df = res['relevance_point']
target_df

0       1
1       0
2       0
3       0
4       1
       ..
7986    1
7987    0
7988    0
7989    0
7990    0
Name: relevance_point, Length: 7991, dtype: int64

In [196]:
features_df = res.iloc[:,1:]
features_df

,abl,abov,acceler,accept,accord,account,achiev,acquir,act,action,...,worst,worth,write,wrong,year,yen,yesterday,yield,york,zero
0,0.000000,0.000000,0.0,0.0,0.143248,0.0,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.037099,0.000000,0.060151,0.451279,0.117518,0.0
1,0.000000,0.045158,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.017583,0.000000,0.000000,0.000000,0.055699,0.0
2,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.076296,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
3,0.000000,0.000000,0.0,0.0,0.025669,0.0,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.039886,0.000000,0.000000,0.000000,0.000000,0.0
4,0.000000,0.084756,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.000000,0.491469,0.053508,0.000000,0.209080,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,0.145532,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.149060,0.000000,0.080560,0.000000,0.078697,0.0
7987,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.036754,0.000000,0.000000,0.000000,0.000000,0.0
7988,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.048461,0.044513,...,0.000000,0.0,0.0,0.0,0.017877,0.000000,0.000000,0.000000,0.000000,0.0
7989,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.035570,0.000000,0.000000,0.000000,0.000000,0.0
7990,0.112909,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,...,0.113694,0.0,0.0,0.0,0.038549,0.000000,0.000000,0.000000,0.061056,0.0

# train-test split

In [197]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(features_df, target_df, test_size=0.3, random_state=42)

In [198]:
train_X.shape

(5593, 1000)

In [199]:
train_y.shape

(5593,)

In [200]:
test_X.shape

(2398, 1000)

In [201]:
test_y.shape

(2398,)

## Try different classifiers

In [207]:
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
#from sklearn.grid_search import GridSearchCV

classifiers = [
    GaussianNB(),
    DecisionTreeClassifier(min_samples_split=40),
    SVC(kernel="rbf", gamma='auto'),
    AdaBoostClassifier(DecisionTreeClassifier(), algorithm="SAMME", n_estimators=200),
    RandomForestClassifier(max_depth=2, random_state=0),
    KNeighborsClassifier(n_neighbors=3),
   # GridSearchCV(SVC(), parameters)
]

In [203]:
import time

PERF_FORMAT_STRING = "\
\tAccuracy: {:>0.{display_precision}f}\tPrecision: {:>0.{display_precision}f}\t\
Recall: {:>0.{display_precision}f}\tF1: {:>0.{display_precision}f}\tF2: {:>0.{display_precision}f}"
RESULTS_FORMAT_STRING = "\tTotal predictions: {:4d}\tTrue positives: {:4d}\tFalse positives: {:4d}\
\tFalse negatives: {:4d}\tTrue negatives: {:4d}"
RUNTIME_FORMAT_STRING = "\tTime for fitting: {:4f}"

def test_classifier(clf, features_train, label_train, features_test, label_test):
    run_time = 0
    start = time.time()
    clf.fit(features_train, label_train)
    end = time.time()
    run_time = max(run_time, round(end-start,3))
    predictions = clf.predict(features_test)
    
    true_negatives = 0
    false_negatives = 0
    true_positives = 0
    false_positives = 0
    
    for prediction, truth in zip(predictions, label_test):
        if prediction == 0 and truth == 0:
            true_negatives += 1
        elif prediction == 0 and truth == 1:
            false_negatives += 1
        elif prediction == 1 and truth == 0:
            false_positives += 1
        elif prediction == 1 and truth == 1:
            true_positives += 1
        else:
            print("Warning: Found a predicted label not == 0 or 1.")
            print("All predictions should take value 0 or 1.")
            print("Evaluating performance for processed predictions:")
            break
    
    try:
        total_predictions = true_negatives + false_negatives + false_positives + true_positives
        accuracy = 1.0*(true_positives + true_negatives)/total_predictions
        precision = 1.0*true_positives/(true_positives+false_positives)
        recall = 1.0*true_positives/(true_positives+false_negatives)
        f1 = 2.0 * true_positives/(2*true_positives + false_positives+false_negatives)
        f2 = (1+2.0*2.0) * precision*recall/(4*precision + recall)
        
        print(clf)
        print(RUNTIME_FORMAT_STRING.format(run_time))
        print(PERF_FORMAT_STRING.format(accuracy, precision, recall, f1, f2, display_precision = 5))
        print(RESULTS_FORMAT_STRING.format(total_predictions, true_positives, false_positives, false_negatives, true_negatives))
        print("")
    except:
        print("Got a divide by zero when trying out:", clf)
        print("Precision or recall may be undefined due to a lack of true positive predicitons.")

### gaussian naive bayes

In [204]:
clf = GaussianNB()
# clf.fit(train_X, train_y)

In [205]:
test_classifier(clf, train_X, train_y, test_X, test_y)

GaussianNB(priors=None, var_smoothing=1e-09)
	Time for fitting: 0.210000
	Accuracy: 0.65304	Precision: 0.29816	Recall: 0.66438	F1: 0.41160	F2: 0.53336
	Total predictions: 2398	True positives:  291	False positives:  685	False negatives:  147	True negatives: 1275

In [208]:
for clf in classifiers:
    test_classifier(clf, train_X, train_y, test_X, test_y)
    print("=========================================================================================================")

GaussianNB(priors=None, var_smoothing=1e-09)
	Time for fitting: 0.192000
	Accuracy: 0.65304	Precision: 0.29816	Recall: 0.66438	F1: 0.41160	F2: 0.53336
	Total predictions: 2398	True positives:  291	False positives:  685	False negatives:  147	True negatives: 1275

=========================================================================================================
DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=40,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')
	Time for fitting: 3.850000
	Accuracy: 0.75146	Precision: 0.29534	Recall: 0.26027	F1: 0.27670	F2: 0.26660
	Total predictions: 2398	True positives:  114	False positives:  272	False negatives:  324	True negatives: 1688

=========================================================================================================
Got a divide by zero when trying out: SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
Precision or recall may be undefined due to a lack of true positive predicitons.
=========================================================================================================
AdaBoostClassifier(algorithm='SAMME',
                   base_estimator=DecisionTreeClassifier(class_weight=None,
                                                         criterion='gini',
                                                         max_depth=None,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort=False,
                                                         random_state=None,
                                                         splitter='best'),
                   learning_rate=1.0, n_estimators=200, random_state=None)
	Time for fitting: 854.702000
	Accuracy: 0.74646	Precision: 0.27394	Recall: 0.23516	F1: 0.25307	F2: 0.24201
	Total predictions: 2398	True positives:  103	False positives:  273	False negatives:  335	True negatives: 1687

=========================================================================================================
Got a divide by zero when trying out: RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=2, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)
Precision or recall may be undefined due to a lack of true positive predicitons.
=========================================================================================================

C:\Users\amita_shukla\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')
	Time for fitting: 0.427000
	Accuracy: 0.78774	Precision: 0.36900	Recall: 0.22831	F1: 0.28209	F2: 0.24716
	Total predictions: 2398	True positives:  100	False positives:  171	False negatives:  338	True negatives: 1789

=========================================================================================================